name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        go: ["^1.15.2"]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: Go ${{ matrix.go }} in ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Environment
        run: |
          go version
          go env

      - name: Install tools
        env:
          GO111MODULE: on
        run: |
          go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.27.0
          golangci-lint --version

      - name: Lint
        run: make lint

      - name: Format
        run: |
          make format-check

      - name: Test
        run: make test

      - name: Build
        run: make build

      - uses: actions/upload-artifact@v1
        if: runner.os == 'linux'
        with:
          name: bin
          path: ./bin

  release:
    name: Release to Github
    if: startsWith(github.ref, 'refs/tags/') && github.repository == 'axetroy/hooker'
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: bin

      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: |
            bin/hooker_darwin_amd64.tar.gz
            bin/hooker_linux_amd64.tar.gz
            bin/hooker_linux_arm64.tar.gz
            bin/hooker_freebsd_amd64.tar.gz
            bin/hooker_openbsd_amd64.tar.gz
            bin/hooker_openbsd_arm64.tar.gz
            bin/hooker_windows_amd64.tar.gz
          draft: false
